<a href="https://colab.research.google.com/github/lcdcustodio/regressao_logistica_sklearn_medconsultor/blob/main/regressao_logistica_sklearn_MedicoConsultor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [139]:
import pandas as pd
base = pd.read_csv('mc_itaim_rev07.csv')

In [140]:
base.head()

Idade      Tipo  ...   IMC Dias Internado
0     70   Eletivo  ...  24.9     X < 5 dias
1     42   Eletivo  ...  42.3     X < 5 dias
2     47   Eletivo  ...  22.0     X < 5 dias
3     53   Eletivo  ...  24.2     X < 5 dias
4     40  Urgencia  ...  26.3     X < 5 dias

[5 rows x 7 columns]

In [141]:
base['Dias Internado'].unique()

array(['X < 5 dias', 'X > 5 dias'], dtype=object)

In [142]:
base.shape

(474, 7)

In [143]:
X = base.iloc[:, 0:6].values
y = base.iloc[:, 6].values

In [144]:
X

array([[70, 'Eletivo', 'ITAIM', '-',
        'Z00 - Exame geral e investigacao de pessoas sem queixas ou diagnostico relatado',
        24.9],
       [42, 'Eletivo', 'ITAIM',
        '30733049 - Osteocondroplastia - estabilizacao  resseccao e/ou plastia  - procedimento videoartroscopico de joelho',
        'Z00 - Exame geral e investigacao de pessoas sem queixas ou diagnostico relatado',
        42.3],
       [47, 'Eletivo', 'ITAIM',
        '31102077 - Colocacao ureteroscopica de duplo J unilateral',
        'N99 - Transtornos do trato geniturinario pos-procedimentos nao classificados em outra parte',
        22.0],
       ...,
       [62, 'Eletivo', 'ITAIM', '-',
        'Z00 - Exame geral e investigacao de pessoas sem queixas ou diagnostico relatado',
        27.0],
       [81, 'Eletivo', 'ITAIM',
        '30912024 - Angioplastia transluminal da aorta ou ramos ou da arteria pulmonar e ramos (por vaso)',
        'Z00 - Exame geral e investigacao de pessoas sem queixas ou diagnostico 

In [145]:
y

array(['X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X > 5 dias', 'X > 5 dias', 'X > 5 dias',
       'X > 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X > 5 dias', 'X < 5 dias', 'X > 5 dias',
       'X > 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X > 5 dias', 'X > 5 dias',
       'X < 5 dias', 'X > 5 dias', 'X > 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X > 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X > 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X > 5 dias', 'X > 5 dias',
       'X > 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X > 5 dias', 'X < 5 dias',
       'X > 5 dias', 'X < 5 dias', 'X > 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5

In [146]:
X[0]

array([70, 'Eletivo', 'ITAIM', '-',
       'Z00 - Exame geral e investigacao de pessoas sem queixas ou diagnostico relatado',
       24.9], dtype=object)

In [147]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
X[:,1] = label_encoder.fit_transform(X[:,1])
X[:,2] = label_encoder.fit_transform(X[:,2])
X[:,3] = label_encoder.fit_transform(X[:,3])
X[:,4] = label_encoder.fit_transform(X[:,4])

In [148]:
X[0]

array([70, 0, 0, 0, 154, 24.9], dtype=object)

In [149]:
from sklearn.model_selection import train_test_split
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size = 0.3)

In [150]:
X_treinamento.shape

(331, 6)

In [151]:
y_treinamento.shape

(331,)

In [152]:
X_teste.shape

(143, 6)

In [153]:
y_teste.shape

(143,)

In [154]:
from sklearn.linear_model import LogisticRegression
classificador = LogisticRegression(max_iter = 10000)
classificador.fit(X_treinamento, y_treinamento)

LogisticRegression(max_iter=10000)

In [155]:
previsoes = classificador.predict(X_teste)

In [156]:
previsoes

array(['X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X > 5 dias',
       'X > 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X > 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X > 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X > 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X > 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X > 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X > 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5

In [157]:
y_teste

array(['X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X > 5 dias',
       'X < 5 dias', 'X > 5 dias', 'X > 5 dias', 'X < 5 dias',
       'X > 5 dias', 'X > 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X > 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X > 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X > 5 dias', 'X > 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X > 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X > 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X < 5 dias', 'X > 5 dias',
       'X > 5 dias', 'X > 5 dias', 'X < 5 dias', 'X > 5 dias',
       'X < 5 dias', 'X > 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X > 5 dias', 'X < 5 dias', 'X < 5 dias',
       'X < 5 dias', 'X < 5 dias', 'X > 5 dias', 'X > 5

In [158]:
from sklearn.metrics import accuracy_score
taxa_acerto = accuracy_score(y_teste, previsoes)
taxa_acerto

0.8181818181818182

In [159]:
base[0:10]

Idade      Tipo  ...   IMC Dias Internado
0     70   Eletivo  ...  24.9     X < 5 dias
1     42   Eletivo  ...  42.3     X < 5 dias
2     47   Eletivo  ...  22.0     X < 5 dias
3     53   Eletivo  ...  24.2     X < 5 dias
4     40  Urgencia  ...  26.3     X < 5 dias
5     53   Eletivo  ...  23.1     X > 5 dias
6     53  Urgencia  ...  23.1     X > 5 dias
7     53  Urgencia  ...  23.1     X > 5 dias
8     53   Eletivo  ...  23.1     X > 5 dias
9     68   Eletivo  ...  25.5     X < 5 dias

[10 rows x 7 columns]

In [171]:
X[1]

array([42, 0, 0, 39, 154, 42.3], dtype=object)

In [172]:
import numpy as np

In [174]:
X_teste_2 = np.array([42, 0, 0, 39, 154, 42.3], dtype=object)

In [175]:
X_teste_2

array([42, 0, 0, 39, 154, 42.3], dtype=object)

In [176]:
temp = X_teste_2.reshape(1, -1)

In [177]:
temp

array([[42, 0, 0, 39, 154, 42.3]], dtype=object)

In [178]:
temp.shape

(1, 6)

In [179]:
previsoes_2 = classificador.predict(temp)

In [181]:
previsoes_2

array(['X < 5 dias'], dtype=object)